spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/Activos_DB
    username: postgres
    password: jose
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
